version: 2
jobs:
  build-and-test:
    macos:
      xcode: 10.0.0
    working_directory: /Users/distiller/project
    environment:
    - FL_OUTPUT_DIR: output
    steps:
    - checkout
    - run:
        name: Run unit tests
        command: bash .circleci/run-tests.sh
    - run:
        name: Bundle install
        command: bundle check || bundle install
    - run: 
        name: Waitting Coverage generated
        command: sleep 5
    - run:
        name: Run Danger
        command: bundle exec danger --verbose
    - run:
        name: Test Coverage
        command: bundle exec slather
    - store_test_results:
        path: output/scan
    - store_artifacts:
        path: output
workflows:
  version: 2
  build-and-test:
    jobs:
    - build-and-test