# .circleci/config.yml
version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    working_directory: /Users/distiller/project/ios
    environment:
    shell: /bin/bash --login -o pipefail
    steps:
      - add-ssh-keys:
          fingerprints:
            - "d7:65:f7:c0:87:1b:e1:f2:0c:9d:e9:dd:9f:c9:f1:fc"
      - type: shell
          name: "Install Dependencies"
          command: git clone git@github.com:myclokInfo/TestRubyRepo.git
      - run:
          name: Set Ruby version
          command: echo "ruby-2.5.1" > ~/.ruby-version
    steps:
      - checkout:
          path: /Users/distiller/project
      - run:
          name: Bundle install
          command: bundle check || bundle install
      - run:
          name: Run unit tests
          command: |
            if [ "${CIRCLE_BRANCH}" == "MOB-1515/smoke-test" ]; then
              bash .circleci/smoke-tests.sh
            fi

            if [ "${CIRCLE_BRANCH}" != "MOB-1515/smoke-test" ]; then
               bash .circleci/run-tests.sh
            fi
            # SCAN_DEVICE: "iPhone 7 (10.3.1)"
            # SCAN_SCHEME: Freshly Dev


      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build