version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
      working_directory: /Users/distiller/project
        environment:
         FL_OUTPUT_DIR: output
        steps:
         - checkout
         - run:
             name: Bundle install
             command: bundle check || bundle install
         - run:
             name: Run Danger
             command: bundle exec danger --verbose
         - run:
             name: Run unit tests
             command: bash .circleci/run-tests.sh

         - store_test_results:
             path: output/scan
         - store_artifacts:
             path: output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - "iOS":
          requires:
            - build
          filters:
            branches:
              ignore: develop